### ISSUE TITLE
Http2Exception Frame length: 14552922 exceeds maximum: 16384

### ISSUE THREAD

**Issue by njimenezotto** [grpc/grpc-java#10830]
Having a grpc server using micronaut-grpc with the following configuration:

```
      grpc:
        server:
          port: 50054
          health.enabled: true
          max-inbound-metadata-size: 300720 # default 8kb 8192
          max-inbound-message-size: 21552922 # default 4194304, max frame size is 16777215
          ssl:
            cert-chain: 'file://etc/nginx/tls/tls.crt'
            private-key: 'file://etc/nginx/tls/tls.key'
```
The server shows on the log:
```
OUTBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=21552922}
```
And having a grpc client with `io.grpc:grpc-netty-shaded:1.59.1` that creates the channel like this:

```
 Grpc.newChannelBuilder(getGrpcServer(), getChannelCredentials())
          .maxInboundMetadataSize(300720)
          .maxInboundMessageSize(21552922)
          .intercept(new TicketClientRequestInterceptor())
          .defaultServiceConfig(getServiceConfig(SERVICE_CONFIG_FILENAME))
          .build();
```

where service config is

```
{
  "loadBalancingConfig": [ { "round_robin": {} } ],
  "healthCheckConfig": {
    "serviceName": ""
  },
  "methodConfig": [
    {
      "name": [{}],
      "timeout": "300s",
      "waitForReady": true,
      "maxResponseMessageBytes": 21852922,
      "maxRequestMessageBytes": 21852922
    }
  ]
}
```

The grpc server sends a big header in `grpc-status-details-bin` and that makes the problem on the grpc client that throws the error:

`Http2Exception Frame length: 14552922 exceeds maximum: 16384`

So am I missing any extra configuration to fit this use case of having a header of ~150-200Kb?
I have looked for a way to increase the max frame size of http2 settings but I don't see how in grpc-java.
I have seen this not merged PR: https://github.com/grpc/grpc-java/pull/7029/files
There is also the grpc args (https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga2ef6e079e5d61b34ce236f50fd38fc83) but I don't see how to inject it in the client.
