### ISSUE TITLE
DnsNameResolver uses Jndi and does not allow to use a different dns resolver

### ISSUE THREAD

**Issue by Necropaw** [grpc/grpc-java#5218]
Please answer these questions before submitting your issue.

### What version of gRPC are you using?
1.17.1

### What did you expect to see?
An easy way to configure a different DNS resource resolver like netty dns because of a bug in the JNDI dns resolver.
In code we want to use a different implementation for `io.grpc.internal.DnsNameResolver.ResourceResolver`

### Background
The implementation of the `DnsNameResolver` uses JNDI to resolve additonial records (like SRV and TXT). Unfortunately the JNDI implementation has a bug so that FQDN have to be used (see. https://bugs.openjdk.java.net/browse/JDK-8170306). 

In our kubernetes environment are multiple namespaces for different stages (e.g.: dev, test, pre, ...) and the bug in OpenJDK requires to use the FQDN for a grpclb address, e.g.: `service-foo-grpclb.dev.svc.cluster.local` instead of just `service-foo-grpclb`.

### Problem
The current implementation has no way to change the resource resolver without reimplementing the `io.grpc.internal.DnsNameResolverProvider` and `io.grpc.internal.DnsNameResolver` (= Copy & Paste over 700 lines of code) because of this:
```
  private static final ResourceResolverFactory resourceResolverFactory =
      getResourceResolverFactory(DnsNameResolver.class.getClassLoader());
``` 
In addition the `DnsNameResolver` contains logic for different cases (like grpc lb - which we need) and is much more than just a simple dns name resolver.

**Comment by carl-mastrangelo** [comment]
Also, as another note, javax.naming is itself pluggable.  You can bring your own at that layer, if you want.  The default we use is `com.sun.jndi.dns.DnsContextFactory`.

**Comment by ejona86** [comment]
Created #5273 for the actual bug (not searching search domains). Closing this since we have no intention of exposing DnsNameResolver as an API.

**Comment by ST-DDT** [comment]
I have the same problem, but I managed to avoid the reimplemenation of the DNSResovler by injecting the namespace as env variable:

````yaml
        env:
        - name: "info.kubernetes.node.name"
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: "info.kubernetes.pod.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "info.kubernetes.pod.namespace"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
````

And then use springs property injection feature to set the target URL:

````properties
grpc.client.foobar.address=dns:/foobar.${info.kubernetes.pod.namespace}.svc.cluster.local
````

or configure the URLs directly via configmaps.

I use [yidongnan/grpc-spring-boot-starter](https://github.com/yidongnan/grpc-spring-boot-starter) for the spring integration.
